;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

unalias=alias /d $1
ls=ls --show-control-chars -F --color $*
~1=~0,-1  
e.=explorer .
pwd=cd
clear=cls
vi=vim $*
brave= start brave  
eoff=@echo echo off  
ps=powershell  
cmderr=cd /d "%CMDER_ROOT%"
hdd=cd /d E:  
adda= git add --all  
upa= git push --all  
g= git $*  
gl=git log --oneline --all --graph --decorate  $*cexe= g++ $1 -Wall -o active $t active.exe  
a= alias $*  
fb= start https://www.facebook.com/  
vid=cd /d E:\videos\ $t explorer .  
desk= chdir /d c:\Users\OmarPc\Desktop\ $t explorer .  
games= cd /d "C:\Users\OmarPc\Documents\game fast\" $t explorer .  
link= cd /d C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
en=@echo $*  
what= "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"  
sound= start https://soundcloud.com  
spot= start https://open.spotify.com/search  
ctf=  C:\Users\%USERNAME%\Desktop\ctfmon.exe  
klctf= taskkill /im ctfmon.exe /f  
standmem= "E:\programs\list maneger\ISLC v1.0.2.8\Intelligent standby list cleaner ISLC.exe"  
cprn=g++ CP.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
log= git log --all --graph --decorate  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
remote2= start https://github.com/orsnaro/CRAFTING_INTERPRETERS_study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
tele=  "C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe"  
stube=start https://www.youtube.com/results?search_query=$1+$2+$3+$4+$5+$6+$7+$8+$9  
hddf=cd /d F:gamesF  
cpp=g++ $* -Wall -Wextra -g -o active $t @echo active.exe is runing .. $t active.exe $t del active.exe  
bmpremote= start https://github.com/orsnaro/Static_chroma_bmp  
interporg=cd c:\Users\OmarPc\repo_CRAFTING_INTERPRETERS_study\  
cpprn=g++ "$*.cpp" -Wall -Wextra -g -o active $t @echo active.exe is runing .. $t active.exe $t del active.exe  
team=C:\Users\OmarPc\AppData\Local\Microsoft\Teams\Update.exe --processStart "Teams.exe"  
allgit=git add --all $t git commit -m "# $*" $t git push  
mspremote= start https://github.com/orsnaro/MSP-MachineLearning-tasks  
cporg=cd /d C:\Users\%USERNAME%\repo_CPP_COMP_study  
bmporg=cd c:\users\%USERNAME%\repo_chroma_bmp_proj\  
org2=cd c:\Users\%USERNAME%\repo_CRAFTING_INTERPRETERS_study\  
msporg=cd c:\Users\%USERNAME%\repo_MSP_ML_study  
shorts=start C:\Users\%USERNAME%\repo_CPP_COMP_study\shortcuts.txt  
allgitall=cd c:\Users\%USERNAME%\repo_MSP_ML_study $t git add --all $t git commit -m "# $*" $t git push $t cd c:\Users\%USERNAME%\repo_CPP_COMP_study $t git add --all $t git commit -m "# $*" $t git push $t cd c:\Users\%USERNAME%\repo_CHROMA_BMP_proj $t git add --all $t git commit -m "# $*" $t git push  
comp=cd /d c:\users\%USERNAME%\repo_CPP_COMP_study $t start  https://codeforces.com/contests $t code cp.cpp $t start  C:\Users\%USERNAME%\AppData\Local\Programs\pomotroid\Pomotroid $t start  https://commons.wikimedia.org/wiki/File:Ascii-proper-color.svg#/media/File:Ascii-proper-color.svg $t calcshift+ctrl+/ (jmp to matching bracket  
py=python -u $*.py  
jptopdf= jupyter-nbconvert --to pdfviahtml $*  
jp= jupyter-lab  
jpn= jupyter notebook  
